# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Group 1:
    - 群组:
        - 百万的大窝:
            href: https://qm.qq.com/q/F2b0lzn5wm
            description: 点击卡片加入群聊【百万的大窝】
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788995930_favicon.ico
            widget:
                type: calendar
                firstDayInWeek: monday # optional - defaults to monday
                view: monthly # optional - possible values monthly, agenda
                maxEvents: 10 # optional - defaults to 10
                showTime: true
                timezone: Asia/Shanghai

    - 🚀百万常用:
        - HomePage 文档:
            href: https://gethomepage.dev/configs/
            description: HomePage 官方文档
            icon: https://imgbed.zhubaiwan.me/file/icons/1744906160197_homepage.png
        - LinuxDo:
            href: https://linux.do/
            description: 一个真诚、友善、团结、专业的社区
            icon: https://avatars.githubusercontent.com/u/160804563
        - 安徽理工大学:
            href: https://www.aust.edu.cn/
            description: 安徽理工大学官网
            icon: https://upload.wikimedia.org/wikipedia/zh/thumb/8/87/AUST_logo.svg/200px-AUST_logo.svg.png
        - Gist:
            href: https://gist.github.com/mine
            description: GitHub Gist 代码片段分享
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788096762_github.png
        # - 大窝飞书文档:
        #     href: https://f0bhyxhlrjd.feishu.cn/wiki/E4JfwScP8i58Pbkzmqgcukjanhe
        #     description: 百万的大窝群规与分享文档
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744905989241_飞书.png
        - 抖音:
            href: https://www.douyin.com/
            description: 抖音-记录美好生活
            icon: https://imgbed.zhubaiwan.me/file/icons/1746105423714_抖音.png
        - Bilibili:
            href: https://www.bilibili.com/watchlater/list/
            description: 一键跳转你的 Bilibili
            icon: https://imgbed.zhubaiwan.me/file/icons/1744904118654_bilibili.png
        - 百万 API:
            href: https://api.zhubaiwan.xyz/console/log
            description: 百万 API 管理 (百万私用)
            icon: https://imgbed.zhubaiwan.me/file/icons/1744795656277_newapi.png
        - Zone.id:
            href: https://my.zone.id/subdomains/2gi4bfiq/url_forwarder/
            description: Zone.id 免费域名
            icon: https://i.111666.best/image/upvDriUv5cIjFO3B01Obqv.png
        # - OpenWebUI:
        #     href: https://chat.zhubaiwan.me/
        #     description: 百万的免费 AI 网站
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788103769_openwebui.png

    - 🌟百万搭建:
        # - 百万API:
        #     href: https://api.zhubaiwan.xyz/console/log
        #     description: 百万 API 管理 (百万私用)
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744795656277_newapi.png
        # - OpenWebUI:
        #     href: https://chat.zhubaiwan.me/
        #     description: 百万的免费 AI 网站
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788103769_openwebui.png
        # - 订阅节点:
        #     href: https://baiwan.zone.id/sub
        #     description: 百万的免费订阅
        #     icon: https://raw.githubusercontent.com/clash-verge-rev/clash-verge-rev/refs/heads/dev/src-tauri/icons/icon.png
        - Sub-Store:
            href: https://sub.zhubaiwan.me/ 
            description: 百万的订阅管理
            icon: https://raw.githubusercontent.com/cc63/ICON/main/Sub-Store.png
        - Subconverter RS:
            href: https://sub.xunka.sbs/
            description: 百万的订阅转换工具
            icon: https://raw.githubusercontent.com/lonelam/subconverter-rs/refs/heads/main/www/public/logo.svg
        - Cloudflare-Worker-Proxy:
            href: http://proxy.zhubaiwan.me/
            description: 基于 CF Worker 的 URL 代理服务
            icon: https://tc.z.wiki/autoupload/F1dJk00XBZ_6bKv7W6dM3xBvV4e-eCpfCDFlwun2bAGyl5f0KlZfm6UsKj-HyTuv/20250705/puI6/200X200/proxy_mirror.png
        - Cloud Mail:
            href: https://lovebw.ggff.net/
            description: 百万的域名邮箱
            icon: https://i.111666.best/image/AbdfamlQ8ZphWybEODKohw.png
        # - CloudPaste:
        #     href: https://cloudpaste.zhubaiwan.me/
        #     description: 百万的云端剪贴板
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1745135835771_cloudpaste.png
        - MoonTV:
            href: http://moontv.zhubaiwan.me/
            description: MoonTV 影视站
            icon: https://raw.githubusercontent.com/senshinya/MoonTV/main/public/logo.png
        - LibreTV:
            href: http://libretv.zhubaiwan.me/
            description: LibreTV 影视站
            icon: https://raw.githubusercontent.com/LibreSpark/LibreTV/refs/heads/main/image/logo.png
        - 百万图床 (New):
            href: https://imgbed.zhubaiwan.me/
            description: 百万的图床 (新)
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788095038_CloudFlare-ImgBed.png
        - 百万图床 (Outdated):
            href: https://pic.lovebw.ddns-ip.net/
            description: 百万的图床 (旧)
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788095038_CloudFlare-ImgBed.png


- Group 2:
    - ☁️开发工具/服务:
        - GitHub:
            href: https://github.com/
            description: GitHub 代码托管平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788096762_github.png
        - Cloudflare:
            href: https://dash.cloudflare.com/
            description: 全球网络安全与性能优化服务
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788099831_cloudflare.png
        - Huggingface:
            href: https://huggingface.co/
            description: HuggingFace 大模型学习社区
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788106434_huggingface.png
        - Claw Cloud:
            href: https://console.run.claw.cloud/
            description: Claw Cloud 应用部署平台
            icon: https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/6925dde13cfb44c694cce5f7b2f3cdab.webp
        - Render:
            href: https://dashboard.render.com/
            description: Render 云托管平台
            icon: https://img.nickyam.com/file/AgACAgUAAyEGAASS2zT1AAIdZWh-V6CA8crYzR9FpAn7FaYOGRvvAAL8xTEbEPTwV2Ij39Z5SoYLAQADAgADeAADNgQ.png
        - Aliyun:
            href: https://cn.aliyun.com/
            description: 阿里云云计算服务平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788095307_ali.png
        # - 腾讯云:
        #     href: https://cloud.tencent.com/
        #     description: 腾讯云云计算服务平台
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744915470468_腾讯云.png
        - Deno:
            href: https://dash.deno.com/
            description: Deno 运行时部署平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788102406_deno.png
        - Vercel:
            href: https://vercel.com/
            description: Vercel 前端部署和服务平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788114258_vercel.png
        - Cloudns:
            href: https://www.cloudns.net/
            description: 域名和 DNS 服务提供商
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788097192_cloudns.png
        - Zone.id:
            href: https://zone.id/
            description: Zone.id 免费域名
            icon: https://i.111666.best/image/upvDriUv5cIjFO3B01Obqv.png
        - Aiven:
            href: https://console.aiven.io/
            description: Aiven 云数据库管理平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788102859_aiven.png
        - Koofr:
            href: https://app.koofr.net/
            description: Koofr 云存储与 WebDAV 服务
            icon: https://imgbed.zhubaiwan.me/file/icons/1744795376085_koofr.png

    - 🌈AI 服务:
        - Google AI Studio:
            href: https://aistudio.google.com/
            description: Google AI 平台
            icon: https://imgbed.zhubaiwan.me/file/icons/1744912926053_Google AI Studio.ico
        - Grok 镜像:
            href: https://grok.dairoot.cn/admin/
            description: 由 xAI 开发的人工智能助手
            icon: https://pbs.twimg.com/media/GkMq1KUbUAAE3U9?format=png
        - QwenChat:
            href: https://chat.qwen.ai/
            description: 阿里 Qwen 官方海外站点
            icon: https://imgbed.zhubaiwan.me/file/icons/1744913596576_Qwen.png
        - Z.ai:
            href: https://chat.z.ai/
            description: THUKEG ChatGLM 官方海外站点
            icon: https://www.aitags.cn/wp-content/uploads/2025/06/1749144527-image.webp
        - 腾讯元宝:
            href: https://yuanbao.tencent.com/
            description: 腾讯元宝 AI 助手
            icon: https://biemoyu.com/wp-content/uploads/2024/06/img_665ca1d0dbc2c.png
        - 豆包:
            href: https://www.doubao.com/
            description: 字节跳动公司开发的 AI 聊天机器人
            icon: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/samantha/logo-icon-white-bg.png
        - DeepSeek:
            href: https://chat.deepseek.com/
            description: 由深度求索公司开发的智能 AI 助手
            icon: https://imgbed.zhubaiwan.me/file/icons/1744916118621_deepseek.png
        - Kimi:
            href: https://www.kimi.com/
            description: 由 Kimi 公司开发的 AI 助手
            icon: https://i0.img2ipfs.com/ipfs/QmNwGZEuW4GCevA4tGjxUR3HWnmaU4AojHy5kyF5VpaZE6?filename=kimi.webp
        - Perplexity:
            href: https://www.perplexity.ai/
            description: Perplexity AI 搜索
            icon: https://imgbed.zhubaiwan.me/file/icons/1744913450715_Perplexity.png
        - You.com:
            href: https://you.com/
            description: You.com 的 AI 聚合网站
            icon: https://imgbed.zhubaiwan.me/file/icons/1746104251505_you.com.webp
        - 当贝 AI:
            href: https://ai.dangbei.com/
            description: 当贝 AI 大模型聚合
            icon: https://simg.doyo.cn/imgfile/bgame/202505/0910003968b3.JPG
        - Duck.ai:
            href: https://duckduckgo.com/?q=1&ia=chat&duckai=1
            description: 由 DuckDuckGo 提供的免费 AI 助手
            icon: https://fullforms.com/images/image/DuckDuckGo_7228.png

    - 🛠️常用工具:
        - 订阅转换:
            href: https://subweb.7li7li.com/
            description: 订阅转换1
            icon: https://tc.z.wiki/autoupload/F1dJk00XBZ_6bKv7W6dM3xBvV4e-eCpfCDFlwun2bAGyl5f0KlZfm6UsKj-HyTuv/20250705/LSbY/200X200/converter.png
        - 订阅转换 2:
            href: https://singbox.nyc.mn/
            description: 订阅转换2
            icon: https://tc.z.wiki/autoupload/F1dJk00XBZ_6bKv7W6dM3xBvV4e-eCpfCDFlwun2bAGyl5f0KlZfm6UsKj-HyTuv/20250705/LSbY/200X200/converter.png
        - PING0:
            href: https://ip.ping0.cc/
            description: IP 查询检测
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788106820_subscription.png
        - 美国地址生成器:
            href: https://www.meiguodizhi.com/
            description: 生成美国地址与虚拟信息
            icon: https://tc.z.wiki/autoupload/F1dJk00XBZ_6bKv7W6dM3xBvV4e-eCpfCDFlwun2bAGyl5f0KlZfm6UsKj-HyTuv/20250705/iffR/200X200/%E5%9C%B0%E5%9D%80.png
        - base64 编码解码:
            href: https://www.toolhelper.cn/EncodeDecode/Base64
            description: base64 编码解码
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788096424_base64.png
        - 油猴脚本:
            href: https://greasyfork.org/zh-CN
            description: 油猴脚本下载
            icon: https://pic.macked.app/static/2601dfda710c35f87d2673aaf13550bc-1702962186.webp
        - Zlibrary:
            href: https://z-library.sk/
            description: Z-library HomePage
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788117323_z-library.png
        - 安娜的档案:
            href: https://zh.annas-archive.org/
            description: 最大的完全开放的图书馆
            icon: https://cdn-1.webcatalog.io/catalog/annas-archive/annas-archive-icon-filled-256.webp
        - 4K 高清壁纸:
            href: https://haowallpaper.com/
            description: 4K 高清壁纸免费下载
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788114946_wallpaper.png
        - Icons:
            href: https://www.iconfont.cn/
            description: 阿里巴巴 icons 图标库
            icon: https://imgbed.zhubaiwan.me/file/icons/1744795791341_ali-icon.png
        - 学习通:
            href: https://i.chaoxing.com/
            description: 超新学习通
            icon: https://imgbed.zhubaiwan.me/file/icons/1744796056894_学习通.png
        - Cherry Studio:
            href: https://www.cherry-ai.com/
            description: 多平台的 AI 客户端
            icon: https://github.com/CherryHQ/cherry-studio/blob/main/build/icon.png?raw=true
